config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  get     :login,  to: 'sessions#new'
  post    :login,  to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  resources :users,       only: [:index, :show, :new, :create]
  resources :followings,  only: [:create, :destroy]
  resources :opinions,    only: [:index, :create, :destroy]
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
  belongs_to :followed, foreign_key: :followed_id, class_name: 'User'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :author_id, presence: true
  validates :text, presence: true, length: { maximum: 140 }

  belongs_to :author, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 15 }
  validates :full_name, presence: true, length: { maximum: 50 }

  has_many :opinions, foreign_key: :author_id, dependent: :delete_all

  has_many :received_followings, foreign_key: :followed_id, class_name: 'Following', dependent: :delete_all
  has_many :followers, through: :received_followings, source: :follower, dependent: :delete_all

  has_many :submitted_followings, foreign_key: :follower_id, class_name: 'Following', dependent: :delete_all
  has_many :followeds, through: :submitted_followings, source: :followed, dependent: :delete_all

  def follower_of?(followed_user)
    followeds.any? { |followed| followed == followed_user }
  end

  def followed_by?(follower_user)
    followers.any? { |follower| follower == follower_user }
  end

  def follow_suggestions
    User.order(created_at: :desc).last(5).filter { |u| !u.followed_by?(self) && u != self }
  end

  after_initialize :set_defaults

  def set_defaults
    self.photo ||= 'default-profile-photo.png'
    self.cover_image ||= 'default-cover-image.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def require_login
    redirect_to login_path, notice: 'You must be logged in to access that page.' unless logged_in?
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    following = Following.new(following_params)
    if following.save
      redirect_to request.referrer, notice: 'Following.'
    else
      redirect_to request.referrer, alert: "Couldn't follow."
    end
  end

  def destroy
    following = Following.find_by(following_params)
    if following.destroy
      redirect_to request.referrer, notice: 'Unfollowing.'
    else
      redirect_to request.referrer, alert: "Couldn't unfollow.."
    end
  end

  private

  def following_params
    params.require(:following).permit(:follower_id, :followed_id)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  def index
    @opinions = Opinion.order(created_at: :desc).includes(:author).limit(10)
    @opinion = Opinion.new
  end

  def create
    @opinion = Opinion.new(opinion_params)
    if @opinion.save
      redirect_to opinions_url, notice: 'Opinion successfully posted!'
    else
      redirect_to request.referrer, alert: 'Opinion not posted. Try again.'
    end
  end

  def destroy
    @opinion = Opinion.find(params[:id])
    if @opinion.destroy
      redirect_to root_path, notice: 'Opinion deleted!'
    else
      redirect_to @opinion, notice: "Opinion couldn't be deleted."
    end
  end

  private

  def opinion_params
    params.require(:opinion).permit(:author_id, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def welcome
    redirect_to opinions_path if logged_in?
  end

  def create
    user = User.find_by(username: params[:username])

    if user
      session[:current_user_id] = user.id
      redirect_to opinions_path, notice: 'Logged in. Welcome!'
    else
      redirect_to new_user_url, notice: 'Username not found! Want to create an account, instead?'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[index new create]

  def index
    @users = User.order(created_at: :desc).limit(10).filter { |u| u != current_user }
  end

  def show
    @user = User.find(params[:id])
    @opinions = @user.opinions.order(created_at: :desc).limit(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path, notice: 'Account successfully created!'
    else
      render :new, notice: 'Account not created. Try again.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :full_name, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def follow_btn(followed_user)
    if current_user == followed_user
      nil
    elsif current_user.follower_of?(followed_user)
      button_to '-', following_path(current_user.id), method: :delete,
                                                      params: { following: {
                                                        follower_id: current_user.id,
                                                        followed_id: followed_user.id
                                                      } },
                                                      class: 'unfollow-btn'
    else
      button_to '+', followings_path,
                params: { following: {
                  follower_id: current_user.id,
                  followed_id: followed_user.id
                } },
                class: 'follow-btn'
    end
  end

  def nav_panel
    render 'layouts/nav_panel' if current_user
  end

  def nav_bar_icons
    render 'layouts/nav_bar_icons' if current_user
  end

  def notice_and_alert
    if notice
      render 'layouts/notice'
    elsif alert
      render 'layouts/alert'
    end
  end
end

app/views/icons/_envelope.html.erb
<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 226 226"
  style=" fill:#000000;">
  <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"
    stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none"
    font-size="none" text-anchor="none" style="mix-blend-mode: normal">
    <path d="M0,226v-226h226v226z" fill="none"></path>
    <g fill="#3a6e97">
      <path d="M188.33333,37.66667h-150.66667c-10.40542,0 -18.83333,8.42792
      -18.83333,18.83333v113c0,10.40542 8.42792,18.83333 18.83333,18.83333h150.66667c10.40542,0
      18.83333,-8.42792 18.83333,-18.83333v-113c0,-10.40542 -8.42792,-18.83333
      -18.83333,-18.83333zM188.33333,75.33333l-75.33333,47.08333l-75.33333,
      -47.08333v-18.83333l75.33333,47.08333l75.33333,-47.08333z">
      </path>
    </g>
  </g>
</svg>

app/views/icons/_magnifier.html.erb
<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 226 226"
  style=" fill:#000000;">
  <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"
    stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none"
    font-size="none" text-anchor="none" style="mix-blend-mode: normal">
    <path d="M0,226v-226h226v226z" fill="none"></path>
    <g fill="#3a6e97">
      <path d="M84.75,18.83333c-36.29323,0 -65.91667,29.62343
      -65.91667,65.91667c0,36.29324 29.62343,65.91667 65.91667,65.91667c16.46031,0
      31.49883,-6.13944 43.0739,-16.1849l4.00944,4.00944v12.17546l56.5,56.5l18.83333,
      -18.83333l-56.5,-56.5h-12.17546l-4.00944,-4.00944c10.04546,-11.57506 16.1849,-26.61358
      16.1849,-43.0739c0,-36.29323 -29.62343,-65.91667-65.91667,-65.91667zM84.75,
      37.66667c26.11494,0 47.08333,20.96839 47.08333,47.08333c0,26.11494 -20.96839,47.08333
      -47.08333,47.08333c-26.11494,0 -47.08333,-20.96839
      -47.08333,-47.08333c0,-26.11494 20.96839,-47.08333 47.08333,-47.08333z"></path>
    </g>
  </g>
</svg>

app/views/icons/_pencil.html.erb
<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 226 226"
  style=" fill:#000000;">
  <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"
    stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none"
    font-size="none" text-anchor="none" style="mix-blend-mode: normal">
    <path d="M0,226v-226h226v226z" fill="none"></path>
    <g fill="#3a6e97">
      <path d="M173.39908,18.83333c-2.40948,0 -4.82163,0.91783
      -6.65788,2.75879l-16.07454,16.07454l37.66667,37.66667l16.07454,-16.07454c3.68192,-3.68192
      3.68192,-9.64326 0,-13.31576l-24.35091,-24.35091c-1.84096,-1.84096 -4.2484,-2.75879
      -6.65788,-2.75879zM136.54167,51.79167l-89.45833,89.45833c0,0 9.46375,0.04708 14.125,4.70833c4.66125,4.66125
      4.5612,13.97786 4.5612,13.97786c0,0 9.60147,0.1848 14.27214,4.85547c4.67067,4.67067
      4.70833,14.125 4.70833,14.125l89.45833,-89.45833zM34.55843,160.08333l-6.30843,37.66667l37.66667,-6.30843z">
      </path>
    </g>
  </g>
</svg>

app/views/layouts/_alert.html.erb
<p class="alert"><%= alert %></p>

app/views/layouts/_nav_bar.html.erb
<div class="nav-bar d-flex">
  <%= image_tag 'logo.png', size: '50', class: "nav-logo" %>
  <%= nav_bar_icons %>
</div>

app/views/layouts/_nav_bar_icons.html.erb
<div class="navbar-icons d-flex">
  <%= render 'icons/pencil' %>
  <%= render 'icons/envelope' %>
  <%= render 'icons/magnifier' %>
  <%= render 'icons/gear' %>
</div>

app/views/layouts/_nav_panel.html.erb
<div class="nav-panel-user d-flex">
  <%= image_tag current_user.photo, size: '60', class: "nav-panel-user-photo" %>
  <%= link_to current_user.full_name, user_path(current_user), class: 'nav-panel-user-name uppercase' %>
</div>

<div class="nav-panel-stats d-flex">
  <div class="d-flex">
    <span class="stats-numbers bold"><%= current_user.followeds.count %></span>
    <span class="stats-label">Following</span>
  </div>
  <div class="d-flex">
    <span class="stats-numbers bold"><%= current_user.followers.count %></span>
    <span class="stats-label">Followers</span>
  </div>
</div>
<div>
  <%= link_to 'Home', opinions_path, class: 'nav-link uppercase bold' %>
  <%= link_to 'Connect', users_path, class: 'nav-link uppercase bold' %>
  <%= link_to 'Profile', user_path(current_user), class: 'nav-link uppercase bold' %>
  <%= button_to 'Log out', logout_path, method: :delete, class: 'nav-link uppercase bold btn-logout' if logged_in? %>
</div>

app/views/layouts/_notice.html.erb
<p class="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goodbooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice_and_alert %>
    <div class="nav-panel"> <%= nav_panel %> </div>
    <%= render 'layouts/nav_bar' %>
    <div class="container">
      <%= yield %>    
    </div>    
  </body>
</html>

app/views/opinions/_form.html.erb
<div class="new_opinion-wrapper latest-opinions">
  <h2 class="new-opinion-heading uppercase bold">Share your opinion on books</h2>
  <%= form_with model: @opinion do |form| %>
    <%= form.label :text, 'Opinion', hidden: true %>
    <%= form.text_area :text, placeholder: 'Compose your opinion here', required: true, class: 'new-opinion-input' %><br><br>
    <%= form.number_field :author_id, value: current_user.id, hidden: true %>
    <%= form.submit 'Share opinion', class: 'button' %>
  <% end %>
</div>

app/views/opinions/index.html.erb
<div class="tabs-bar d-flex">
  <%= link_to "Opinions", opinions_path, class: "tab-item uppercase bold" %>
</div>

<main class="main-content">
  <div class="new_opinion">
    <%= render 'opinions/form' %>
  </div>
  <div class="latest-opinions">
    <% @opinions.each do |opinion| %>
      <div class="opinion-card d-flex">
        <%= image_tag opinion.author.photo, size: '60', class: 'opinion-card-image' %>
        <div>
          <%= link_to opinion.author.full_name, user_path(opinion.author), class: 'opinion-card-author bold' %>
          <span class="opinion-date"><%= time_ago_in_words(opinion.created_at) %></span>
          <p class="opinion-card-text"><%= opinion.text %></p>
        </div>
      </div>
    <% end %>
  </div>
</main>

<div class="right-panel">
  <div class="who-to-follow-section">
    <div class="right-panel-section-heading bold uppercase">
      Who to follow
    </div>
    <div class="right-panel-section-wrapper">
      <% current_user.follow_suggestions.each do |u| %>
        <div class="who-to-follow-card d-flex">
          <%= image_tag u.photo, size: '60', class: 'who-to-follow-photo' %>
          <div class="who-to-follow-name-wrap d-flex">
            <%= link_to u.full_name, user_path(u), class: 'who-to-follow-name bold' %>
            <%= link_to "@#{u.username}", user_path(u), class: 'who-to-follow-username' %>
          </div>
          <%= follow_btn(u) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, class: 'form' do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username, minlength: 3, maxlength: 15, required: true %><br><br>
  <%= form.label :full_name %>
  <%= form.text_field :full_name, minlength: 3, maxlength: 50, required: true %><br><br>
  <%= form.label :photo, "Photo URL (preferably square, or it might be distorted)" %>
  <%= form.text_field :photo %><br><br>
  <%= form.label :cover_image, "Cover image URL" %>
  <%= form.text_field :cover_image %><br><br>
  <%= form.submit "Submit", class: 'button' %>
<% end %>

app/views/users/index.html.erb
<div class="tabs-bar d-flex">
  <%= link_to "People", users_path, class: "tab-item uppercase bold" %>
</div>

<main class="main-content">
  <div class="latest-opinions">
    <% @users.each do |user| %>
      <div class="who-to-follow-card d-flex connect-card">
        <%= image_tag user.photo, size: '60', class: 'who-to-follow-photo' %>
        <div class="who-to-follow-name-wrap d-flex">
          <%= link_to user.full_name, user_path(user), class: 'who-to-follow-name bold' %>
          <%= link_to "@#{user.username}", user_path(user), class: 'who-to-follow-username' %>
        </div>
        <%= follow_btn(user) %>
      </div>
    <% end %>
  </div>
</main>

<div class="right-panel">
  <div class="profile-followers-section">
    <div class="right-panel-section-heading bold uppercase">
      Your Followers
    </div>
    <div class="right-panel-section-wrapper">
      <% current_user.followers.each do |u| %>
        <div class="who-to-follow-card d-flex">
          <%= image_tag u.photo, size: '60', class: 'who-to-follow-photo' %>
          <div class="who-to-follow-name-wrap d-flex">
            <%= link_to u.full_name, user_path(u), class: 'who-to-follow-name bold' %>
            <%= link_to "@#{u.username}", user_path(u), class: 'who-to-follow-username' %>
          </div>
          <%= follow_btn(u) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-container">
  <h1>Create Account</h1>

  <%= render 'form' %>

  <br><br><p>Don't have an account?</p><br><br>
  <%= link_to 'Log in', login_path, class: 'button' %>
</div>

app/views/users/show.html.erb
<div class="cover-image-wrapper">
  <%= image_tag @user.cover_image, class: 'cover-image' %>
</div>

<div class="tabs-bar d-flex">
  <%= link_to "Opinions", opinions_path, class: "tab-item uppercase bold" %>
</div>

<main class="main-content profile-opinions">
  <div class="latest-opinions">
    <% @opinions.each do |opinion| %>
      <div class="opinion-card d-flex">
        <%= image_tag opinion.author.photo, size: '60', class: 'opinion-card-image' %>
        <div>
          <%= link_to opinion.author.full_name, user_path(opinion.author), class: 'opinion-card-author bold' %>
          <span class="opinion-date"><%= time_ago_in_words(opinion.created_at) %></span>
          <p class="opinion-card-text"><%= opinion.text %></p>
        </div>
      </div>
    <% end %>
  </div>
</main>

<div class="right-panel">
  <div class="profile-section">
    <div class="profile-info d-flex">
      <div class="profile-actions-wrapper d-flex">
        <span class="profile-actions-items d-flex"><%= follow_btn(@user) %></span>
        <span class="profile-actions-items d-flex"><%= image_tag @user.photo, size: '100', class: 'profile-photo' %></span>
        <span class="profile-actions-items d-flex"></span>
      </div>
      <h2 class="profile-full-name uppercase bold"><%= @user.full_name %></h2>
      <p class="profile-username">@<%= @user.username %></p>
    </div>
    <div class="profile-stats d-flex">
      <div class="d-flex">
        <span class="stats-profile-numbers bold"><%= @user.opinions.count %></span>
        <span class="stats-label">Opinions</span>
      </div>
      <div class="d-flex">
        <span class="stats-profile-numbers bold"><%= @user.followeds.count %></span>
        <span class="stats-label">Following</span>
      </div>
      <div class="d-flex">
        <span class="stats-profile-numbers bold"><%= @user.followers.count %></span>
        <span class="stats-label">Followers</span>
      </div>
    </div>
  </div>
  <div class="profile-followers-section">
    <div class="right-panel-section-heading bold uppercase">
      Followed by
    </div>
    <div class="right-panel-section-wrapper">
      <% @user.followers.each do |u| %>
        <div class="who-to-follow-card d-flex">
          <%= image_tag u.photo, size: '60', class: 'who-to-follow-photo' %>
          <div class="who-to-follow-name-wrap d-flex">
            <%= link_to u.full_name, user_path(u), class: 'who-to-follow-name bold' %>
            <%= link_to "@#{u.username}", user_path(u), class: 'who-to-follow-username' %>
          </div>
          <%= follow_btn(u) %>
        </div>
      <% end %>
    </div>
  </div>
</div>